#!/usr/bin/env bash
# =============================================================================
# RIPPLE Uninstall Script for Linux/macOS
# =============================================================================
# This script removes files generated by quickstart.sh:
#   - Conda environment (ripple-env)
#   - Generated launchers and shortcuts
#   - Build artifacts (target/)
#   - Auto-installed Maven (tools/)
#
# This script does NOT uninstall:
#   - Java/JDK
#   - Conda/Miniconda/Anaconda
#   - System-installed Maven
# =============================================================================

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}${BLUE}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              RIPPLE Uninstall Script                     ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo "This will remove all files generated by RIPPLE quickstart:"
echo "  - Conda environment (ripple-env)"
echo "  - Build artifacts and generated files"
echo "  - Desktop shortcuts and menu entries"
echo "  - Auto-installed Maven (if any)"
echo ""
echo "This will NOT uninstall Java, Conda, or system Maven."
echo ""
echo "The source code and configuration files will be preserved."
echo ""

read -p "Are you sure you want to continue? [y/N]: " CONFIRM
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Uninstall cancelled."
    exit 0
fi

echo ""
echo "Uninstalling RIPPLE..."
echo ""

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Detect OS
OS=$(uname -s)

# =============================================================================
# Initialize Conda (needed to remove environment)
# =============================================================================
CONDA_ENV_NAME="${CONDA_ENV_NAME:-ripple-env}"
CONDA_BIN=""
CONDA_SHELL_READY=false

find_conda_bin() {
    local candidates=()
    local path

    path="$(command -v conda 2>/dev/null || true)"
    if [[ -n "$path" ]]; then
        candidates+=("$path")
    fi
    if [[ -n "${CONDA_EXE:-}" ]]; then
        candidates+=("${CONDA_EXE}")
    fi

    candidates+=(
        "$HOME/miniconda3/bin/conda"
        "$HOME/anaconda3/bin/conda"
        "$HOME/miniforge3/bin/conda"
        "$HOME/mambaforge/bin/conda"
        "/opt/anaconda3/bin/conda"
        "/opt/miniconda3/bin/conda"
        "/opt/homebrew/Caskroom/miniconda/base/bin/conda"
        "/opt/homebrew/Caskroom/miniforge/base/bin/conda"
        "/usr/local/Caskroom/miniconda/base/bin/conda"
        "/usr/local/Caskroom/miniforge/base/bin/conda"
    )

    local c
    for c in "${candidates[@]}"; do
        if [[ -x "$c" ]]; then
            echo "$c"
            return 0
        fi
    done

    return 1
}

init_conda_shell() {
    local conda_bin="$1"
    local hook
    if [[ -z "$conda_bin" ]]; then
        return 1
    fi
    hook="$("${conda_bin}" shell.bash hook 2>/dev/null)" || return 1
    eval "$hook" >/dev/null 2>&1 || return 1
    return 0
}

CONDA_BIN="$(find_conda_bin || true)"
if [[ -n "$CONDA_BIN" ]]; then
    if init_conda_shell "$CONDA_BIN"; then
        CONDA_SHELL_READY=true
    fi
fi

# =============================================================================
# Remove Conda environment
# =============================================================================
echo -e "${BLUE}[1/7] Removing conda environment...${NC}"
if [[ -z "$CONDA_BIN" ]]; then
    echo -e "  ${YELLOW}!${NC} Conda not found. Skipping env removal."
    echo -e "    If you have conda installed, run: conda env remove -n ${CONDA_ENV_NAME}"
elif "${CONDA_BIN}" env list 2>/dev/null | grep -Eq "^[* ]*${CONDA_ENV_NAME}[[:space:]]"; then
    if [[ "${CONDA_SHELL_READY}" == "true" ]]; then
        conda deactivate 2>/dev/null || true
    fi
    if "${CONDA_BIN}" env remove -n "${CONDA_ENV_NAME}" -y >/dev/null 2>&1; then
        echo -e "  ${GREEN}✓${NC} Conda environment '${CONDA_ENV_NAME}' removed"
    else
        echo -e "  ${YELLOW}!${NC} Could not remove conda environment '${CONDA_ENV_NAME}'"
        echo -e "    Try: conda deactivate && conda env remove -n ${CONDA_ENV_NAME}"
    fi
else
    echo -e "  ${GREEN}✓${NC} Conda environment not found (already removed)"
fi

# =============================================================================
# Remove desktop shortcuts (Linux)
# =============================================================================
echo -e "${BLUE}[2/7] Removing desktop shortcuts...${NC}"
REMOVED_SHORTCUTS=0

if [[ "$OS" == "Linux" ]]; then
    # Remove desktop shortcut
    if [[ -f "${HOME}/Desktop/RIPPLE.desktop" ]]; then
        rm -f "${HOME}/Desktop/RIPPLE.desktop"
        ((REMOVED_SHORTCUTS++))
    fi
    
    # Remove applications menu entry
    if [[ -f "${HOME}/.local/share/applications/ripple.desktop" ]]; then
        rm -f "${HOME}/.local/share/applications/ripple.desktop"
        ((REMOVED_SHORTCUTS++))
    fi
elif [[ "$OS" == "Darwin" ]]; then
    # Remove macOS desktop alias
    if [[ -f "${HOME}/Desktop/RIPPLE.command" ]] || [[ -L "${HOME}/Desktop/RIPPLE.command" ]]; then
        rm -f "${HOME}/Desktop/RIPPLE.command"
        ((REMOVED_SHORTCUTS++))
    fi
fi

if [[ $REMOVED_SHORTCUTS -gt 0 ]]; then
    echo -e "  ${GREEN}✓${NC} Removed $REMOVED_SHORTCUTS desktop shortcut(s)"
else
    echo -e "  ${GREEN}✓${NC} No desktop shortcuts found"
fi

# =============================================================================
# Remove generated launchers
# =============================================================================
echo -e "${BLUE}[3/7] Removing generated launchers...${NC}"
REMOVED_LAUNCHERS=0

for launcher in RIPPLE.sh RIPPLE.bat RIPPLE.command RIPPLE.desktop; do
    if [[ -f "${SCRIPT_DIR}/${launcher}" ]]; then
        rm -f "${SCRIPT_DIR}/${launcher}"
        ((REMOVED_LAUNCHERS++))
    fi
done

echo -e "  ${GREEN}✓${NC} Removed $REMOVED_LAUNCHERS launcher file(s)"

# =============================================================================
# Remove build artifacts
# =============================================================================
echo -e "${BLUE}[4/7] Removing build artifacts...${NC}"
if [[ -d "${SCRIPT_DIR}/target" ]]; then
    rm -rf "${SCRIPT_DIR}/target"
    echo -e "  ${GREEN}✓${NC} target/ directory removed"
else
    echo -e "  ${GREEN}✓${NC} target/ directory not found"
fi

# =============================================================================
# Remove auto-installed Maven
# =============================================================================
echo -e "${BLUE}[6/7] Removing auto-installed tools...${NC}"
if [[ -d "${SCRIPT_DIR}/tools" ]]; then
    rm -rf "${SCRIPT_DIR}/tools"
    echo -e "  ${GREEN}✓${NC} tools/ directory removed (local Maven)"
else
    echo -e "  ${GREEN}✓${NC} tools/ directory not found"
fi

# =============================================================================
# Remove Python cache
# =============================================================================
echo -e "${BLUE}[7/7] Cleaning up cache files...${NC}"
find "${SCRIPT_DIR}" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
find "${SCRIPT_DIR}" -type f -name "*.pyc" -delete 2>/dev/null || true
echo -e "  ${GREEN}✓${NC} Python cache cleaned"

echo ""
echo -e "${BOLD}${GREEN}══════════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}              RIPPLE Uninstall Complete                        ${NC}"
echo -e "${BOLD}${GREEN}══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "The following have been removed:"
echo "  - Conda environment (ripple-env)"
echo "  - Desktop shortcuts and menu entries"
echo "  - Generated launchers (RIPPLE.sh, etc.)"
echo "  - Build artifacts (target/)"
echo "  - Auto-installed Maven (tools/)"
echo ""
echo "Source code and configuration files have been preserved."
echo "You can delete this folder to completely remove RIPPLE."
echo ""
