@echo off
REM =============================================================================
REM RIPPLE Uninstall Script for Windows
REM =============================================================================
REM This script removes files generated by quickstart.bat:
REM   - Conda environment (ripple-env)
REM   - Generated launchers and shortcuts
REM   - Build artifacts (target/)
REM   - Auto-installed Maven (tools/)
REM
REM This script does NOT uninstall:
REM   - Java/JDK
REM   - Conda/Miniconda/Anaconda
REM   - System-installed Maven
REM =============================================================================

setlocal EnableDelayedExpansion

echo.
echo +==========================================================+
echo ^|              RIPPLE Uninstall Script                     ^|
echo +=========================================================+
echo.
echo This will remove all files generated by RIPPLE quickstart:
echo   - Conda environment (ripple-env)
echo   - Build artifacts and generated files
echo   - Desktop shortcuts
echo   - Auto-installed Maven (if any)
echo.
echo This will NOT uninstall Java, Conda, or system Maven.
echo.
echo The source code and configuration files will be preserved.
echo.

set /p "CONFIRM=Are you sure you want to continue? [y/N]: "
if /i not "%CONFIRM%"=="y" (
    echo.
    echo Uninstall cancelled.
    pause
    exit /b 0
)

echo.
echo Uninstalling RIPPLE...
echo.

cd /d "%~dp0"

REM =============================================================================
REM Initialize Conda (needed to remove environment)
REM =============================================================================
if exist "%USERPROFILE%\miniconda3\Scripts\activate.bat" (
    call "%USERPROFILE%\miniconda3\Scripts\activate.bat" "%USERPROFILE%\miniconda3"
) else if exist "%USERPROFILE%\Miniconda3\Scripts\activate.bat" (
    call "%USERPROFILE%\Miniconda3\Scripts\activate.bat" "%USERPROFILE%\Miniconda3"
) else if exist "%USERPROFILE%\anaconda3\Scripts\activate.bat" (
    call "%USERPROFILE%\anaconda3\Scripts\activate.bat" "%USERPROFILE%\anaconda3"
) else if exist "%USERPROFILE%\Anaconda3\Scripts\activate.bat" (
    call "%USERPROFILE%\Anaconda3\Scripts\activate.bat" "%USERPROFILE%\Anaconda3"
) else if exist "%LOCALAPPDATA%\miniconda3\Scripts\activate.bat" (
    call "%LOCALAPPDATA%\miniconda3\Scripts\activate.bat" "%LOCALAPPDATA%\miniconda3"
) else if exist "%PROGRAMDATA%\miniconda3\Scripts\activate.bat" (
    call "%PROGRAMDATA%\miniconda3\Scripts\activate.bat" "%PROGRAMDATA%\miniconda3"
) else if defined CONDA_EXE (
    for %%I in ("%CONDA_EXE%") do set "CONDA_DIR=%%~dpI.."
    if exist "!CONDA_DIR!\Scripts\activate.bat" (
        call "!CONDA_DIR!\Scripts\activate.bat" "!CONDA_DIR!"
    )
)

REM =============================================================================
REM Remove Conda environment
REM =============================================================================
echo [1/6] Removing conda environment...
call conda env list 2>nul | findstr /C:"ripple-env" >nul 2>&1
if not errorlevel 1 (
    call conda deactivate 2>nul
    call conda env remove -n ripple-env -y >nul 2>&1
    if not errorlevel 1 (
        echo   [OK] Conda environment 'ripple-env' removed
    ) else (
        echo   [WARN] Could not remove conda environment
    )
) else (
    echo   [OK] Conda environment not found (already removed)
)

REM =============================================================================
REM Remove desktop shortcut
REM =============================================================================
echo [2/6] Removing desktop shortcut...
if exist "%USERPROFILE%\Desktop\RIPPLE.lnk" (
    del "%USERPROFILE%\Desktop\RIPPLE.lnk" 2>nul
    echo   [OK] Desktop shortcut removed
) else (
    echo   [OK] Desktop shortcut not found
)

REM =============================================================================
REM Remove generated launchers
REM =============================================================================
echo [3/6] Removing generated launchers...
set REMOVED_LAUNCHERS=0
if exist "%~dp0RIPPLE.bat" (
    del "%~dp0RIPPLE.bat" 2>nul
    set /a REMOVED_LAUNCHERS+=1
)
if exist "%~dp0RIPPLE.sh" (
    del "%~dp0RIPPLE.sh" 2>nul
    set /a REMOVED_LAUNCHERS+=1
)
if exist "%~dp0RIPPLE.command" (
    del "%~dp0RIPPLE.command" 2>nul
    set /a REMOVED_LAUNCHERS+=1
)
if exist "%~dp0RIPPLE.desktop" (
    del "%~dp0RIPPLE.desktop" 2>nul
    set /a REMOVED_LAUNCHERS+=1
)
echo   [OK] Removed %REMOVED_LAUNCHERS% launcher file(s)

REM =============================================================================
REM Remove build artifacts
REM =============================================================================
echo [4/6] Removing build artifacts...
if exist "%~dp0target" (
    rmdir /s /q "%~dp0target" 2>nul
    echo   [OK] target/ directory removed
) else (
    echo   [OK] target/ directory not found
)

REM =============================================================================
REM Remove auto-installed Maven
REM =============================================================================
echo [6/6] Removing auto-installed tools...
if exist "%~dp0tools" (
    rmdir /s /q "%~dp0tools" 2>nul
    echo   [OK] tools/ directory removed (local Maven)
) else (
    echo   [OK] tools/ directory not found
)

REM =============================================================================
REM Remove Python cache
REM =============================================================================
if exist "%~dp0src\main\python\__pycache__" (
    rmdir /s /q "%~dp0src\main\python\__pycache__" 2>nul
)

echo.
echo +==========================================================+
echo ^|              RIPPLE Uninstall Complete                   ^|
echo +==========================================================+
echo.
echo The following have been removed:
echo   - Conda environment (ripple-env)
echo   - Desktop shortcut
echo   - Generated launchers (RIPPLE.bat, etc.)
echo   - Build artifacts (target/)
echo   - Auto-installed Maven (tools/)
echo.
echo Source code and configuration files have been preserved.
echo You can delete this folder to completely remove RIPPLE.
echo.
pause

endlocal
